config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :site_contacts
  resources :sites

  root to: 'visitors#index'
  devise_for :users
  resources :users
  match '/s/:short_title', to: "visitors#show", via: :get
end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_filter :authenticate_auth
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :width, :height, :os, :preview_image, :vertical_bg, :horizontal_bg, :screen_size)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= simple_form_for(@device) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :width %>
    <%= f.input :height %>
    <%= f.input :os %>
    <%= f.input :preview_image %>
    <%= f.input :vertical_bg %>
    <%= f.input :horizontal_bg %>
    <%= f.input :screen_size %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Width</th>
      <th>Height</th>
      <th>Os</th>
      <th>Preview image</th>
      <th>Vertical bg</th>
      <th>Horizontal bg</th>
      <th>Screen size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.width %></td>
        <td><%= device.height %></td>
        <td><%= device.os %></td>
        <td><%= device.preview_image %></td>
        <td><%= device.vertical_bg %></td>
        <td><%= device.horizontal_bg %></td>
        <td><%= device.screen_size %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Width:</strong>
  <%= @device.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @device.height %>
</p>

<p>
  <strong>Os:</strong>
  <%= @device.os %>
</p>

<p>
  <strong>Preview image:</strong>
  <%= @device.preview_image %>
</p>

<p>
  <strong>Vertical bg:</strong>
  <%= @device.vertical_bg %>
</p>

<p>
  <strong>Horizontal bg:</strong>
  <%= @device.horizontal_bg %>
</p>

<p>
  <strong>Screen size:</strong>
  <%= @device.screen_size %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>