config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :site_contacts
  resources :sites

  root to: 'visitors#index'
  devise_for :users
  resources :users
  match '/s/:short_title', to: "visitors#show", via: :get
end

app/models/site_contact.rb
class SiteContact < ActiveRecord::Base
  belongs_to :site

  attr_accessor :url
end

app/controllers/site_contacts_controller.rb
class SiteContactsController < ApplicationController
  before_filter :authenticate_auth, except: [:new, :create]
  before_action :set_site_contact, only: [:show, :edit, :update, :destroy]

  # GET /site_contacts
  # GET /site_contacts.json
  def index
    #@site_contacts = SiteContact.all
  end

  # GET /site_contacts/1
  # GET /site_contacts/1.json
  def show
  end

  # GET /site_contacts/new
  def new
    @site_contact = SiteContact.new
  end

  # GET /site_contacts/1/edit
  def edit
  end

  # POST /site_contacts
  # POST /site_contacts.json
  def create
    @site_contact = SiteContact.new(site_contact_params)
    @site_contact.site_id = get_site(site_contact_params[:url]).try(:id)

    respond_to do |format|
      if @site_contact.save
        #send notice to admin
        if Rails.env == 'production'
          SmsSendWorker.perform_async(ENV['ADMIN_PHONE'].split('|').join(','), "#{@site_contact.phone}给你留言了：#{@site_contact.site.domain}【摩适配】")
        end

        format.html { render text: 'success' }
        format.json { render action: 'show', status: :created, location: @site_contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @site_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_contacts/1
  # PATCH/PUT /site_contacts/1.json
  def update
    respond_to do |format|
      if @site_contact.update(site_contact_params)
        format.html { redirect_to @site_contact, notice: 'Site contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_contact }
      else
        format.html { render :edit }
        format.json { render json: @site_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_contacts/1
  # DELETE /site_contacts/1.json
  def destroy
    @site_contact.destroy
    respond_to do |format|
      format.html { redirect_to site_contacts_url, notice: 'Site contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_contact
      @site_contact = SiteContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_contact_params
      params.require(:site_contact).permit(:site_id, :url, :email, :qq, :phone, :is_processed, :note)
    end
end

app/helpers/site_contacts_helper.rb
module SiteContactsHelper
end

app/views/site_contacts/_form.html.erb
<%= simple_form_for(@site_contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :site %>
    <%= f.input :email %>
    <%= f.input :qq %>
    <%= f.input :phone %>
    <%= f.input :is_processed %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/site_contacts/edit.html.erb
<h1>Editing site_contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_contact %> |
<%= link_to 'Back', site_contacts_path %>

app/views/site_contacts/index.html.erb
<h1>Listing site_contacts</h1>

<table>
  <thead>
    <tr>
      <th>Site</th>
      <th>Email</th>
      <th>Qq</th>
      <th>Phone</th>
      <th>Is processed</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_contacts.each do |site_contact| %>
      <tr>
        <td><%= site_contact.site %></td>
        <td><%= site_contact.email %></td>
        <td><%= site_contact.qq %></td>
        <td><%= site_contact.phone %></td>
        <td><%= site_contact.is_processed %></td>
        <td><%= site_contact.note %></td>
        <td><%= link_to 'Show', site_contact %></td>
        <td><%= link_to 'Edit', edit_site_contact_path(site_contact) %></td>
        <td><%= link_to 'Destroy', site_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site contact', new_site_contact_path %>

app/views/site_contacts/new.html.erb
<h1>New site_contact</h1>

<%= render 'form' %>

<%= link_to 'Back', site_contacts_path %>

app/views/site_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site:</strong>
  <%= @site_contact.site %>
</p>

<p>
  <strong>Email:</strong>
  <%= @site_contact.email %>
</p>

<p>
  <strong>Qq:</strong>
  <%= @site_contact.qq %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @site_contact.phone %>
</p>

<p>
  <strong>Is processed:</strong>
  <%= @site_contact.is_processed %>
</p>

<p>
  <strong>Note:</strong>
  <%= @site_contact.note %>
</p>

<%= link_to 'Edit', edit_site_contact_path(@site_contact) %> |
<%= link_to 'Back', site_contacts_path %>