config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :site_contacts
  resources :sites

  root to: 'visitors#index'
  devise_for :users
  resources :users
  match '/s/:short_title', to: "visitors#show", via: :get
end

app/models/site.rb
class Site < ActiveRecord::Base
  default_scope {order('created_at DESC')}

  before_create :create_unique_short_title

  validates :domain, presence: true
  
  private
    def create_unique_short_title
      begin
        self.short_title = self.domain.gsub(/\./, '-')
        self.short_title = SecureRandom.hex(2) if self.class.exists?(:short_title => short_title)
      end while self.class.exists?(:short_title => short_title)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_auth
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.page(params[:page])
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:domain, :title, :keywords, :description, :is_processed, :note)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<div class="col-md-10 col-md-offset-1">
  <%= simple_form_for(@site) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :domain %>
      <%= f.input :short_title %>
      <%= f.input :title %>
      <%= f.input :keywords %>
      <%= f.input :description %>
      <%= f.input :is_processed %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/sites/edit.html.erb
<div class="container">
  <h1>编辑站点</h1>

  <%= render 'form' %>

  <hr/>
  <%= link_to '返回', sites_path %>
</div>

app/views/sites/index.html.erb
<h2>网站列表</h2>
<table class="table table-brodered">
  <thead>
    <tr>
      <th>编号</th>
      <th>域名</th>
      <th>访问</th>
      <th>创建时间</th>
      <th>处理状态</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.id %></td>
        <td><%= site.domain %></td>
        <td><%= link_to '访问网站', 'http://' + site.domain.to_s, target: '_blank' %> | <%= link_to '适配预览', "/s/#{site.short_title}", target: '_blank' %></td>
        <td><%= site.created_at.to_s(:db) %>(<%= distance_of_time_in_words_to_now(site.created_at) %>前)</td>
        <td><%= site.is_processed %></td>
        <td><%= link_to '详细', site %></td>
        <td><%= link_to '编辑', edit_site_path(site) %></td>
        <td><%= link_to '删除', site, method: :delete, data: { confirm: '确定删除?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @sites %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<h1><%= @site.domain %></h1>
<table class="table table-bordered">
  <tr><td width="120px">域名：</td><td><%= link_to @site.domain, 'http://' + @site.domain, target: '_blank' %></td></tr>
  <tr><td>短地址：</td><td><%= @site.short_title %></td></tr>
  <tr><td>标题：</td><td><%= @site.title %></td></tr>
  <tr><td>关键词：</td><td><%= @site.keywords %></td></tr>
  <tr><td>描述：</td><td><%= @site.description %></td></tr>
  <tr><td>处理状态：</td><td><%= @site.is_processed %></td></tr>
</table>
<%= link_to '编辑', edit_site_path(@site) %> | 
<%= link_to '返回', sites_path %>